services:
  coredns:
    image: coredns/coredns:latest
    command: ["-conf", "/etc/coredns/Corefile"]
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile:ro
      - ./coredns/zones:/zones:ro
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on: [coredns]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./pki:/etc/nginx/certs:ro
    restart: unless-stopped
